apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: diseases-create-batchs
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-diseases
              image: nexus.lestoises.ch/cron-diseases
              imagePullPolicy: IfNotPresent
              command:
                - php
                - /var/www/html/bin/console
                - t4s:diseases
                - reportInstitution
                - fribourg
          restartPolicy: Never
