apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: diseases-report
spec:
  schedule: "*/55 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-diseases
              image: nexus.lestoises.ch/cron-diseases:1.2
              imagePullPolicy: IfNotPresent
              command:
                - php
                - /var/www/html/bin/console
                - t4s:diseases
                - report
          restartPolicy: Never
