apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: diseases-run-batchs
spec:
  schedule: "*/6 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-diseases
              image: nexus.lestoises.ch/cron-diseases:0.3
              imagePullPolicy: IfNotPresent
              command:
                - php
                - /var/www/html/bin/console
                - t4s:diseases
                - runBatchs
          restartPolicy: Never
