apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: diseases-create-batchs
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-diseases
              image: nexus.lestoises.ch/cron-diseases:1.13
              imagePullPolicy: IfNotPresent
              command:
                - php
                - /var/www/html/bin/console
                - t4s:diseases
                - create
          restartPolicy: Never
