apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: diseases-report-institutions-sion
spec:
  schedule: "0 18 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-diseases
              image: nexus.lestoises.ch/cron-diseases:1.9
              imagePullPolicy: IfNotPresent
              command:
                - php
                - /var/www/html/bin/console
                - t4s:diseases
                - reportInstitution
                - sion
          restartPolicy: Never
